# mkdocs config https://www.mkdocs.org/user-guide/configuration/#configuration

site_name: !ENV [SITE_NAME, 'My site name']
site_url: https://avdata99.github.io/test-mkdocs/
site_description: |
  This is the site description
  (a test version)
site_author: Andres andres@data99.com.ar
copyright: Creative commons BY-SA. No rigths reserved @avdata99

repo_url: https://github.com/avdata99/test-mkdocs
edit_uri: edit/main/docs

nav:
    - Home: index.md
    - About: 
        - General: about/about.md
        - License: about/license.md
    - Test page: test-page.md
    - Issue tracker: https://github.com/avdata99/test-mkdocs/issues

# theme: readthedocs
theme: material
    
plugins:
    - search:
        indexing: 'full'
        lang:
            - en
            - es
    # - mkpdfs:
    #     company: OKFN
    #     author: Some OKFN member <some@okfn.org>
    - with-pdf:
        author: Some OKFN member <some@okfn.org>
        copyright: OKFN CC BY-SA
        cover: true
        back_cover: true
        cover_title: Cover title
        cover_subtitle: Cover subtitle
        cover_logo: https://okfn.org/assets/img/OKF-logo-white-background.png
        # custom path for cover.html and/or style.css
        custom_template_path: pdf-template
        toc_title: Table of contents
        heading_shift: false
        toc_level: 3
        ordered_chapter_level: 2
        #excludes_children:
        #    - 'release-notes/:upgrading'
        #    - 'release-notes/:changelog'
        #
        #exclude_pages:
        #    - 'bugs/'
        #    - 'appendix/contribute/'
        #convert_iframe:
        #    - src: IFRAME SRC
        #      img: POSTER IMAGE URL
        #      text: ALTERNATE TEXT
        #    - src: ...
        #two_columns_level: 3
        #
        #render_js: true
        #headless_chrome_path: headless-chromium
        #
        output_path: pdf/doc.pdf
        #enabled_if_env: ENABLE_PDF_EXPORT
        #
        #debug_html: true
        show_anchors: true
        verbose: true
extra_css:
    - css/custom.css

extra_javascript:
    - https://code.jquery.com/jquery-3.5.1.min.js
    - js/app.js

# extra_templates: []

# extra: A set of key-value pairs, where the values can be any valid YAML 
# construct, that will be passed to the template.
extra:
    version: 0.1.5
    okfn_url: https://okfn.org
    scoda_url: https://schoolofdata.org

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
